language: php
php:
  - '7.1'

before_install:
  - composer install
script: phpunit --coverage-clover=coverage.xml --configuration phpunit.xml --bootstrap vendor/autoload.php tests

after_success:
  - bash <(curl -s https://codecov.io/bash)