language: php
php:
  - '7.2'

before_install:
  - composer install
script: vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.xml --configuration phpunit.xml tests

after_success:
  - bash <(curl -s https://codecov.io/bash)